defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

redcloth:
  hard_breaks: true

url: "/gtfs_engine"

theme: jekyll-theme-hacker